#' plotting genome feature and synteny maps
#'
#' @param data contig_layout generated by layout_genomes
#' @param ... passed through to geom_contig
#' @importFrom ggplot2 ggplot
#' @export
#' @return ggplot object
gggenomes <- function(data = NULL, mapping = aes(), ...){
    envir <- parent.frame()

    p <- ggplot(data = data, environment = envir)
    class(p) <- c('gggenomes', class(p))
    p
}

#' ggplot.default tries to \code{fortify(data)}
#'
#' @export
ggplot.tbl_genomes <- function(data, mapping = aes(), ...,
                               environment = parent.frame()) {
  if (!missing(mapping) && !inherits(mapping, "uneval")) {
    stop("Mapping should be created with `aes() or `aes_()`.", call. = FALSE)
  }

  p <- structure(list(
    data = data,
    layers = list(),
    scales = ggplot2:::scales_list(),
    mapping = mapping,
    theme = list(),
    coordinates = coord_cartesian(default = TRUE),
    facet = facet_null(),
    plot_env = environment
  ), class = c("gg", "ggplot"))

  p$labels <- ggplot2:::make_labels(mapping)

  ggplot2:::set_last_plot(p)
  p
}

#' gggenomes default theme
#' @importFrom ggplot2 theme_bw
#' @importFrom ggplot2 theme
#' @export
#' @return ggplot theme
theme_genomes <- function(){
    theme_bw() + theme(
        panel.border = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = "white"),
        axis.title.x=element_blank(),
        axis.title.y=element_blank(),
        axis.ticks.y=element_blank())
}

#' y scale with genome labels
#'
#' @import ggplot2
#' @export
#' @return ggplot scale object
scale_y_genomes <- function(data, ...){
    scale_y_reverse(
        breaks=unique(expose(data)$gix),
        labels=unique(expose(data)$gid), ...)
}
